version: "3"

services:

  bot:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: news
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"